name: Upload Website

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Build
      run: |
        npm i
        echo "CONTENTFUL_SPACE_ID=$SPACE_ID" >> .env
        echo "CONTENTFUL_ACCESS_TOKEN=$ACCESS_TOKEN" >> .env
        echo "MAILCHIMP_ENDPOINT=$MAILCHIMP_ENDPOINT" >> .env
        npm i gatsby -g
        gatsby build
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        SPACE_ID: ${{ secrets.SPACE_ID }}
        MAILCHIMP_ENDPOINT: 'https://example.us10.list-manage.com/subscribe/post?u=123'

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./public s3://${{ secrets.AWS_S3_BUCKET }}
